import Head from 'next/head'
import Image from 'next/image'

import Format from '../Layout/format'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Farm Fresh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

       

    <Format>
      
    </Format>
          
        

    </div>
  )
}
